---
language: ruby
services:
    - docker
branches:
    only:
        - master
env:
   global:
    - DEST_ID=forge
    - NSVER=7
    - DOCKER_IMAGE=nethserver/makerpms:buildsys${NSVER}
    - >
        EVARS="
        -e DEST_ID
        -e TRAVIS_BRANCH
        -e TRAVIS_BUILD_ID
        -e TRAVIS_PULL_REQUEST_BRANCH
        -e TRAVIS_PULL_REQUEST
        -e TRAVIS_REPO_SLUG
        -e TRAVIS_TAG
        -e NSVER
        -e ENDPOINTS_PACK
        "

script: >
    docker run -ti --name makerpms1 ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s sope.spec
    && docker commit makerpms1 nethserver/build1
    && docker run -ti --name makerpms2 ${EVARS}
    --hostname b${TRAVIS_BUILD_NUMBER}.nethserver.org
    --volume $PWD:/srv/makerpms/src:ro ${DOCKER_IMAGE} makerpms-travis -s sogo.spec
    && docker commit makerpms2 nethserver/build2
    && { docker cp nethserver/build1:/srv/makerpms/RPMS - | docker cp - nethserver/build2:/srv/makerpms/ ; }
    && docker run -ti ${EVARS}
    -e SECRET
    -e SECRET_URL
    -e AUTOBUILD_SECRET
    -e AUTOBUILD_SECRET_URL
    nethserver/build2 uploadrpms-travis
